[package]
name = "bgc"
version = "0.2.0"
edition = "2021"
authors = ["Aria Fibla"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
terminal-menu = "3.0.0"
