[package]
name = "bgc"
version = "0.3.1"
edition = "2021"
authors = ["Aria Fibla"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
dirs = "5.0.1"
terminal-menu = "3.0.0"
